apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "infra-litellm-rest"
  name: "infra-litellm-rest"
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: "infra-litellm-rest"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        p1.cn/metric_path: /metrics
        p1.cn/scrape_port: "4000"
        p1.cn/should_be_scraped: "true"
        proxy.istio.io/config: |
          terminationDrainDuration: 20s
          holdApplicationUntilProxyStarts: true
      labels:
        app:infra-litellm-rest 
    spec:
      containers:
          image: {{image-url}}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            httpGet:
              path: /debug/health
              port: 4000
              scheme: HTTP
            timeoutSeconds: 5
          name: "infra-litellm-rest"
          readinessProbe:
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              path: /debug/health
              port: 4000
              scheme: HTTP
            timeoutSeconds: 10
          resources:
            limits:
              cpu: "8"
              memory: 16Gi
            requests:
              cpu: "1m"
              memory: 1Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
      securityContext: { }
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 15
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 15