model_list:
  # - model_name: thinking-us.anthropic.claude-3-7-sonnet-20250219-v1:0
  #   litellm_params:
  #     model: bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
  #     thinking: {"type": "enabled", "budget_tokens": 1024}
  #     max_tokens: 1080
  #     merge_reasoning_content_in_choices: true
general_settings: 
  master_key: sk-1234 # [OPTIONAL] Use to enforce auth on proxy. See - https://docs.litellm.ai/docs/proxy/virtual_keys
  store_model_in_db: True
  proxy_budget_rescheduler_min_time: 60
  proxy_budget_rescheduler_max_time: 64
  proxy_batch_write_at: 1
  database_connection_pool_limit: 10
  database_url: "postgresql://postgres:postgres@127.0.0.1:5432/litellm" # [OPTIONAL] use for token-based auth to proxy 


